### PR TITLE
standardise treatment of fused heads

### PR DESCRIPTION
**Pull request by aryamanarora**
In draft state.

### CODE REVIEW

**Comment by aryamanarora** [comment]
@nschneid Here is one tricky case, due to the N being gapped and our previous wholesale conversion of "which" from N to D. Is this actually a fused head?

https://github.com/nert-nlp/cgel/blob/ece92751cb3bf59264d77c3c43d834dd9e817144/datasets/twitter.cgel#L2565-L2568

**Comment by aryamanarora** [comment]
Unrelated to fused head, this line is also raising an error per my modified fused head checks. Looks like a duplicated node:

https://github.com/nert-nlp/cgel/blob/ece92751cb3bf59264d77c3c43d834dd9e817144/datasets/ewt.cgel#L4042-L4043

This and the previous comment are the only errors raised by the fused head checks after these changes.

**Comment by nschneid** [comment]
1st one: This hurts my brain but I think you're right—this is the dependent use of "which" with a gap, so just `:Det` not `:Det-Head`. And the NP seems to be missing a Nom.

2nd one: I think the whole Head-Prenucleus should be under the first `:Mod (Clause_rel` per the new policy. In a fused relative (or relative clause with a WH-relativizer) there are two `Clause_rel` levels, one containing the prenucleus and one not.

**Comment by aryamanarora** [comment]
Looks good, merging

**Pull request merged**
