### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by BrettRey**

### CODE REVIEW

**Comment by nschneid** [comment]
Ooh exciting! Is it possible to have a version with page numbers? It would be super useful for looking up the context of the example.

**Comment by BrettRey** [comment]
Very likely, but I don't know how to do it. If you can put together some kind of MS script that would do that to examples in a .doc file, I'd happily run it and then strip out the examples again.

**Comment by BrettRey** [comment]
Now that I think about it, the pagination in the doc file isn't the same as the book. So there would have to be some process where a quote is taken from the .doc and found in the PDF, and the page # would have to be retrieved there and the added back into the example. I have no idea about how to do this.

**Comment by nschneid** [comment]
Were the doc files produced from the PDF?

**Comment by BrettRey** [comment]
No, the were produced from the original Word Perfect files.

**Comment by nschneid** [comment]
This is a good opportunity for me to try ChatGPT's code generation capabilities.

**Comment by nschneid** [comment]
OK this looks very doable with the pypdf library. It can extract the text from each page (there will be some extra spaces but that doesn't matter if we're just checking which page each example is on).

**Comment by BrettRey** [comment]
fantastic!

**Comment by nschneid** [comment]
I think the Word files need to be saved as .docx though

**Comment by nschneid** [comment]
Here's my progress so far: extracting page numbers for examples up to page 50.

[examples_pagenums_pp1-50.txt](https://github.com/nert-nlp/cgel/files/12384823/examples_pagenums_pp1-50.txt)

It goes through the .docx file paragraph by paragraph and heuristically checks that at least the first 10 or last 10 non-space characters are in the PDF page. Some of the phonetic symbols, for example, would throw it off if checking exactly.

If it can't match the paragraph but can match the subsequent paragraph, the one that wasn't matched receives `???` instead of a page number.

The script can't handle trees.

There are some differences between the manuscript and the PDF. For example:

- p. 31 [3] has different content words in the example, so the script needs to make an exception
- p. 33 [21] has "dative case:" in the manuscript where it is just "dative:" in the PDF (the heuristics ignore this difference)

**Comment by nschneid** [comment]
Yeah we don't want to lose underlines, bolds, or small caps. I'm looking into HTML conversion.

**Comment by nschneid** [comment]
@BrettRey Do you have ch. 5 & ch. 14?

**Pull request merged**
